#Simple of previous version before edits:

name: QA CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
        # 1️ Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

        # 2️ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

#       # 3 Install dependencies
      - name: Install dependencies
        run: |
            npm install
            echo "✅ Dependencies installed."

        # 4 Run automated tests with report generation
 
      - name: Run automated tests
        run: |
            npm test
            echo "✅ Automated tests completed."
